################################################################################
MLI_FILE		= cordova_datepicker.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-plugin-datepicker
################################################################################
